spring.application.name=ecom-application

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?options=-c%20TimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL

management.endpoints.web.exposure.include=beans,health
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

server.info.env.enabled=true
server.shutdown=graceful

info.app.name=MyNewApp
info.app.description=App build by us
info.app.version=1.0.0
